### PR TITLE
Introduce prometheus annotations

### PR DESCRIPTION
**Pull request by iocanel**
The goal of this pull request is to add intiial support for prometheus annotations. 
It introduced `EnableServiceMonitor` which will generate a ServiceMonitor for the application.

The service monitor requires the prometheus operator, in order to work. Once its created the operator will take care of monitoring the application.

### CODE REVIEW

**Comment by iocanel** [comment]
@geoand: completely agree on the the tighter framework integration.

I'll try to have a look over the weekend.

**Comment by geoand** [comment]
> @geoand: completely agree on the the tighter framework integration.
> 
> I'll try to have a look over the weekend.

Let me know if we want an extra pair of hands :)

**Comment by iocanel** [comment]
@geoand: How about #117 ?

**Comment by geoand** [comment]
Looks good! If I have some time to spare, I'll pick it up next week

**Pull request merged**
