### PR TITLE
Have KubernetesAnnotationProcessor run when other framework annotations present

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Should address ##222

I imagine we might need to add other annotations as well, just not sure what other ones we need to add

### CODE REVIEW

**Comment by geoand** [comment]
Seems good to me! @iocanel, WDYT ?

**Comment by iocanel** [comment]
This is something that would work, but I am not very comfortable with crossing boundaries and have framework references outside of the framework modules.

Moreover, I think that this is more of a workaround to a specific use case, instead of the actual problem which is about config order. 

My understanding is that #222 is caused because some `configurators` are applied before the actual config is in place. And this is something that can be manifested in a lot of diffrerent ways too (e.g. config provided by annotations and overriden by properties etc).

I'd like to experiement with it a for couple of days, before we can greenlight this PR.

**Comment by iocanel** [comment]
Some more details:

When no annotation is found for one of the available Hanlders (Kubernetes, Openshift and so on) we currently use `handleDefault`which ignores all configuration configurators/visitors. The result is that we ignore everything configured in framework modules.

I am experiementing with applying configuratiors/visitors to the `default` config.

**Comment by ryanjbaxter** [comment]
Thanks @iocanel, I agree, I did not like mixing frameworks into the core kubernetes annotation code....just wasnt sure how else to approach it....I am sure you will find something better :)

**Comment by iocanel** [comment]
@ryanjbaxter I merged #242. If this solves your problem, then we can close this one.

**Pull request closed without merging**
