### PR TITLE
fix: set the correct supported source version on processors.

### PR DESCRIPTION
**Pull request by iocanel**
There is an annoying warning when using the processors with java8+ that can potentially cause confusion. This pull request addresses this issue.

### CODE REVIEW

**Comment by geoand** [comment]
@iocanel Should `@SupportedSourceVersion(SourceVersion.RELEASE_8)` be added to all annotation processors?

**Comment by iocanel** [comment]
@geoand: yeah

**Comment by geoand** [comment]
In that case, `SpringBootMappingProcessor` and `DockerBuildAnnotationProcessor` are missing the annotation :)

**Comment by geoand** [comment]
@iocanel see my previous comment :)

**Comment by iocanel** [comment]
done

**Comment by geoand** [comment]
Cool

**Pull request merged**
