### PR TITLE
fix (#172): Use the containerPort instead of the hostPort as the rout…

### PR DESCRIPTION
**Pull request by iocanel**
…e targetPort.

### CODE REVIEW

**Comment by geoand** [comment]
Maybe we should add an integration test that uses a `Route`?

**Comment by geoand** [comment]
Actually @iocanel would you like to compile a list of nice to have end to end tests so I can start putting them together?

**Comment by iocanel** [comment]
@geoand: The problem with the integration test, is that `host` is cluster specific.

**Comment by geoand** [comment]
Wouldn't the host just `someip.nip.io` for the integration tests?

**Comment by iocanel** [comment]
@geoand: Yeah for integration tests that would do

**Pull request merged**
